People:
#   - Name : "Example"
#     Day : "2021-1-12"  # 日期格式为yyyy-MM-dd，若不知道年份则设置为0000
#     Calendar : "lunar"  # 阴历：lunar 阳历：solar
#     DistanceConfig : 3  # 设置生日提前几天提醒, 最大为3, 0为当天提醒
  - Name: "DaD"
    Day: "1977-7-23"
    Calendar: "lunar"
    DistanceConfig : 1
  - Name: "爷爷"
    Day: "0000-12-22"
    Calendar: "lunar"
    DistanceConfig : 1
  - Name: "奶奶"
    Day: "0000-5-10"
    Calendar: "lunar"
    DistanceConfig : 1
  - Name: "MoM"
    Day: "1978-12-3"
    Calendar: "lunar"
    DistanceConfig : 1
  - Name: "陈jh"
    Day: "2004-3-29"
    Calendar: "lunar"
    DistanceConfig: 1
  - Name: "秦xm"
    Day: "0000-10-12"
    Calendar: "solar"
    DistanceConfig: 1
  - Name: "欧阳zt"
    Day: "0000-9-19"
    Calendar: "lunar"
    DistanceConfig: 1
  - Name: "周bg"
    Day: "0000-11-7"
    Calendar: "lunar"
    DistanceConfig: 1
  - Name: "杨z"
    Day: "0000-05-27"
    Calendar: "lunar"
    DistanceConfig: 1
  - Name: "王rj"
    Day: "0000-10-23"
    Calendar: "lunar"
    DistanceConfig: 1
  - Name: "凌k"
    Day: "0000-11-26"
    Calendar: "lunar"
    DistanceConfig: 1
